export {
  createMoneySirenDbClient,
  type MoneySirenDbClient,
  type MoneySirenDbClientOptions,
} from "./client.js";
export {
  getPendingMigrations,
  MIGRATIONS,
  runMigrations,
  type Migration,
  type MigrationExecutor,
  type MigrationRunResult,
} from "./migrate.js";
export {
  EMERGENCY_ACTION_RUNS_SQL,
  INITIAL_SCHEMA_SQL,
  LOCAL_AI_USAGE_DAILY_SQL,
  REQUIRED_TABLES,
  type RequiredTable,
} from "./schema.js";
export { resolveSqliteBin, SQLITE_BIN_ENV_KEY } from "./sqlite-bin.js";
export {
  initializeLocalStore,
  recordEmergencyActionRun,
  readLocalStore,
  readLocalAiUsageHistory,
  recordLocalReportRun,
  saveLocalAiUsageDaily,
  saveLocalProviderCollection,
  type LocalAlertInput,
  type LocalAlertRecord,
  type LocalBillingSnapshotInput,
  type LocalBillingSnapshotRecord,
  type LocalCostEstimateInput,
  type LocalCostEstimateRecord,
  type LocalEmergencyActionRunInput,
  type LocalEmergencyActionRunRecord,
  type LocalAiUsageCoverage,
  type LocalAiUsageDailyInput,
  type LocalAiUsageGranularity,
  type LocalAiUsageHistoryQuery,
  type LocalAiUsageHistoryRow,
  type LocalAiUsageProviderKey,
  type LocalAiUsageSourceScope,
  type LocalStore,
  type LocalStoreOptions,
  type LocalProviderCollectionInput,
  type LocalProviderRecord,
  type LocalReportRunInput,
  type LocalReportRunRecord,
  type LocalServiceHealthSnapshotInput,
  type LocalServiceHealthSnapshotRecord,
  type LocalUsageSnapshotInput,
  type LocalUsageSnapshotRecord,
} from "./local-store.js";
